# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  schedule:
    - cron: "50 23 * * *"  # runs at 23:50 at night and saves the today submissions
  workflow_dispatch:     # Manual run button

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      ENV: ${{ secrets.ENV }}
      LEETCODE_USERNAME: ${{ secrets.LEETCODE_USERNAME }}
      LEETCODE_SESSION: ${{ secrets.LEETCODE_SESSION }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.3'

    - name: Install Dependencies
      run: go mod tidy

    - name: Run Script
      run: go run main.go
